final FIXED_FPS : Int = 60;
final FIXED_ITERATIONS : Int = 8;

final PLAYER_DEFAULT_MOVEMENT_SPEED : Float = 60.0;
final PLAYER_FOCUS_MOVEMENT_SPEED : Float = 30.0;
final PLAYER_HITBOX_RADIUS : Float = 6.0;
final PLAYER_GRAZEBOX_RADIUS : Float = 16.0;